class_name EmbodimentProtocolPackageIdentity
extends RefCounted

## Generated by scripts/build_embodiment_protocol_lock.py. Do not edit by hand.

const SHA256 := "8986b451670694677873749acdce29bd3eda4acf9c3088f24b126f4e83ab2e67"
