class_name EmbodimentProtocolPackageIdentity
extends RefCounted

## Generated by scripts/build_embodiment_protocol_lock.py. Do not edit by hand.

const SHA256 := "ddfc8998dfe33c0bb68aff31f78118a227792f4d568bd438d732c3d3abe0c34d"
