#!/usr/bin/env python3
"""Regenerate the evolving pre-release embodiment protocol package lock."""

from __future__ import annotations

import argparse
from pathlib import Path

from genesis_arena.embodiment.protocol import EmbodimentProtocolPackage, canonical_json_bytes
from worldarena.paths import WORLDARENA_ROOT

PIN_RELATIVE_PATH = Path(
    "godot/scripts/embodiment/protocol/embodiment_protocol_package_identity.gd"
)


def _pin_bytes(package_sha256: str) -> bytes:
    return (
        "class_name EmbodimentProtocolPackageIdentity\n"
        "extends RefCounted\n\n"
        "## Generated by scripts/build_embodiment_protocol_lock.py. Do not edit by hand.\n\n"
        f'const SHA256 := "{package_sha256}"\n'
    ).encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repository-root",
        type=Path,
        default=WORLDARENA_ROOT,
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    package = EmbodimentProtocolPackage.from_repository(
        args.repository_root, verify_lock=False
    )
    lock = package.build_lock()
    expected = canonical_json_bytes(lock) + b"\n"
    path = package.root / package.LOCK_NAME
    pin_path = args.repository_root.resolve() / PIN_RELATIVE_PATH
    expected_pin = _pin_bytes(str(lock["package_sha256"]))
    if args.check:
        if (
            not path.is_file()
            or path.read_bytes() != expected
            or not pin_path.is_file()
            or pin_path.read_bytes() != expected_pin
        ):
            raise SystemExit("embodiment protocol lock is stale or non-canonical")
        return 0
    path.write_bytes(expected)
    pin_path.parent.mkdir(parents=True, exist_ok=True)
    pin_path.write_bytes(expected_pin)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
